### ISSUE TITLE
Bridge系のRepositoryいらない

### ISSUE THREAD

**Issue by mirror-kt** [brokenManager/devlaza-back#27]
https://github.com/brokenManager/devlaza-back/blob/2defee332880ae74aad72425cd333cfe250d2ffd/src/main/kotlin/com/approvers/devlazaApi/repository/Project.kt#L27

これ以外にもあると思うけど
`@ManyToMany` `@OneToMany` `@ManyToOne`っていうリレーション表現用のアノテーションがあるので勝手にやってくれる(はず)

**Comment by isso0424** [comment]
一旦保留させてクレメンス...
