### ISSUE TITLE
Autowiredについて

### ISSUE THREAD

**Issue by mirror-kt** [brokenManager/devlaza-back#32]
https://github.com/brokenManager/devlaza-back/blob/2defee332880ae74aad72425cd333cfe250d2ffd/src/main/kotlin/com/approvers/devlazaApi/controller/UserController.kt#L21

`private lateinit var`ってAutowiredできたっけ
setterがprivateになるから参照できないような気がする

**Comment by isso0424** [comment]
参照できてその後の処理もできているのでClose

**Comment by mirror-kt** [comment]
コンストラクタインジェクションの方がいい気はする

**Comment by isso0424** [comment]
#とは

**Comment by mirror-kt** [comment]
```kotlin
class Hoge
@Autowired
constructor(
    private val hogeRepository: HogeRepository,
    private val sender: MailSender
) {
    // do something
}
```
みたいに、コンストラクタ自体に`@Autowired`付けれる。
もしくは
```kotlin
class Hoge
constructor(
    private val hogeRepository: HogeRepository,
    @Autowired private val sender: MailSender
) {
    // do something
}
```
みたいに、コンストラクタの指定フィールドだけAutowiredもできる。

**Comment by isso0424** [comment]
#47
