### ISSUE TITLE
これは何ですか

### ISSUE THREAD

**Issue by mirror-kt** [brokenManager/devlaza-back#33]
https://github.com/brokenManager/devlaza-back/blob/2defee332880ae74aad72425cd333cfe250d2ffd/src/main/kotlin/com/approvers/devlazaApi/controller/UserController.kt#L25

`showId`が何なのかよくわかってないですが、ユーザーを一意に識別できるものならListで返すのはまずそう

**Comment by isso0424** [comment]
showIdはtwitterの@.hogefugaみたいなやつだね
これってList以外で返そうとするとどうなるんだ?

**Comment by mirror-kt** [comment]
```kotlin
fun getUserByShowId(@PathVariable(value="id") id: String): ResponseEntity<User>{
     val user = userRepository.findByShowId(id).single()
     return ResponseEntity.ok(user)
}
```
`List#single`でListの要素が一つの時要素そのものに変換できる。
1つじゃない時は例外が投げられる。
catchするか、そんなことはあり得ないとして握り潰すかは任せる。
