### ISSUE TITLE
Int? to Int

### ISSUE THREAD

**Issue by mirror-kt** [brokenManager/devlaza-back#38]
https://github.com/brokenManager/devlaza-back/blob/2defee332880ae74aad72425cd333cfe250d2ffd/src/main/kotlin/com/approvers/devlazaApi/controller/ProjectsController.kt#L109

```kotlin
val recruiting: Int = rawRecruiting.toIntOrNull() ?: 1
```
エルビス演算子使おうね

**Comment by isso0424** [comment]
そういやこれ #48 でやったわ
