### ISSUE TITLE
getProject(UUID)

### ISSUE THREAD

**Issue by mirror-kt** [brokenManager/devlaza-back#39]
https://github.com/brokenManager/devlaza-back/blob/2defee332880ae74aad72425cd333cfe250d2ffd/src/main/kotlin/com/approvers/devlazaApi/controller/ProjectsController.kt#L166

```kotlin
return projectsList.singleOrNull()
```

**Comment by isso0424** [comment]
`singleOrNull()`...そんなものもあるのか...
