### ISSUE TITLE
トークン生成がまずい

### ISSUE THREAD

**Issue by mirror-kt** [brokenManager/devlaza-back#40]
https://github.com/brokenManager/devlaza-back/blob/2defee332880ae74aad72425cd333cfe250d2ffd/src/main/kotlin/com/approvers/devlazaApi/controller/UserController.kt#L87

これはまずい

**Comment by mirror-kt** [comment]
OAuthするか、JWTトークンとかを使うべき

**Comment by isso0424** [comment]
べんつよから開始します

**Comment by isso0424** [comment]
JWTトークンでやるわ

**Comment by isso0424** [comment]
ん?これだとJWTTでは
