### ISSUE TITLE
Tableのインデックス

### ISSUE THREAD

**Issue by mirror-kt** [brokenManager/devlaza-back#43]
検索で使用するカラム(nameなど)はインデックス貼ってください。

**Comment by mirror-kt** [comment]
`@Table(indexes = Index(name = "member_index", columnList = "NAME,ID", unique = true ))`

**Comment by mirror-kt** [comment]
IndexはIDとは別物
辞書でいう目次的なものを生成しておくことで検索を高速化する

**Comment by isso0424** [comment]
!MEMO: Tableの定義時に貼っておく
