### ISSUE TITLE
検索系の実装

### ISSUE THREAD

**Issue by mirror-kt** [brokenManager/devlaza-back#44]
検索アルゴリズム、というか絞り込む方法を別のクラスに分けておくことでいい気分になれます。

**Comment by isso0424** [comment]
一応ProjectSearchに置いてあるが完全丸投げにしたほうがいいのか?

**Comment by mirror-kt** [comment]
`Searcher`インターフェイスを作って、具体的な検索方法はSearcherインターフェイスの実装が担う。
ProjectSearchはSearcherインターフェイスを受け取って実際に検索を行う。

```kotlin
interface Searcher<T> {
    fun search(value: T): Boolean
}
```

んで
```kotlin
class ProjectSearch {
    fun search(searcher: Searcher): SearchResult {
        val values = findAll()
        val res = values.filter { searcher.search(it) }
        // TODO
    }
}
```
みたいな
この例はあまりいい書き方ではないので真似しちゃいけないんだけどこういう感じ

**Comment by isso0424** [comment]
じゃあinterfaceでは検索方法とかの指定はしない感じか

**Comment by mirror-kt** [comment]
検索方法は実装任せ

**Comment by isso0424** [comment]
なるなる
実装にぶん投げた値を元に検索方法を変えるって感じか

**Comment by mirror-kt** [comment]
微妙に違う
これは俺が出した例が悪いんだが
Strategyパターンってのがある
https://qiita.com/i-tanaka730/items/4d00c884b7ce1594f42a

**Comment by mirror-kt** [comment]
検索方法をごっそり変えることができるようになる

**Comment by mirror-kt** [comment]
(それをSQLレベルに反映させるのがむずいかも知らんが)

**Comment by isso0424** [comment]
やってみるわ
thx

**Comment by isso0424** [comment]
要するにアルゴリズムのinterfaceを実装しておいてそれの実装として検索方法を置くって話か

で、変えたくなったら使う実装を切り替えると

**Comment by mirror-kt** [comment]
そうねー
ProjectSearcherにメソッドがめちゃくちゃ乱立するよりはクラスとして検索方法を切り出せるこっちの方がいい。

**Comment by isso0424** [comment]
_**†完全に理解した†**_
