### ISSUE TITLE
テストコード書いてください

### ISSUE THREAD

**Issue by mirror-kt** [brokenManager/devlaza-back#60]

**Comment by isso0424** [comment]
`createFirstTestCode`で作業するわ

**Comment by isso0424** [comment]
#64 でテストの基盤を整えたので
`genarateTestCodes` で書いていく

**Comment by mirror-kt** [comment]
すっげぇどうでもいいんだけどgenerateって生成するって意味だからブランチ名微妙だな()

**Comment by isso0424** [comment]
←知っててgenerateにした人
`writeTestCodes`とかの方が適切か？

**Comment by isso0424** [comment]
modelのtestを書こう
